### PR TITLE
WIP: replace SharpRaven with Sentry

### PR DESCRIPTION
**Pull request by knocte**
Fixes https://github.com/nblockchain/geewallet/issues/86

### CODE REVIEW

**Comment by knocte** [comment]
@webwarrior-ws THIS PR IS ON HOLD: WE DONT NEED IT ANYMORE BECAUSE WE'RE GOING TO DO ANOTHER APPROACH: FINISH PR #253

**Comment by knocte** [comment]
> BECAUSE WE'RE GOING TO DO ANOTHER APPROACH: FINISH PR https://github.com/nblockchain/geewallet/pull/253

And in case I wasn't clear: I am going to finish that PR, I don't need help on this one.

**Comment by knocte** [comment]
@webwarrior-ws even though I'm not sure if I'll merge this PR soon, let's rebase it (and change it to use 4.0.3 instead of a prerelease/beta version), so that it's ready to merge when we need it.

**Comment by webwarrior-ws** [comment]
> @webwarrior-ws even though I'm not sure if I'll merge this PR soon, let's rebase it (and change it to use 4.0.3 instead of a prerelease/beta version), so that it's ready to merge when we need it.

@knocte done

**Comment by webwarrior-ws** [comment]
Superseded by #296

**Pull request closed without merging**
