### PR TITLE
Backend(LN): catch NOnionException TorOperations

### PR DESCRIPTION
**Pull request by parhamsaremi**
Catch the NOnionException after the Retries have finished and the problem still exists. We catch the exception and return an error.

Fixes https://github.com/nblockchain/geewallet/issues/181 
Fixes https://github.com/nblockchain/geewallet/issues/182

### CODE REVIEW

**Comment by knocte** [comment]
@aarani please review

**Comment by knocte** [comment]
> Fixes https://github.com/nblockchain/geewallet/issues/181

Are you sure? I think this is false ^

**Comment by knocte** [comment]
> @aarani please review

ping

**Comment by aarani** [comment]
LGTM

**Comment by knocte** [comment]
> LGTM

Are you sure? Why are we replacing specific exception types with generic exception types in this PR? I don't understand.

**Comment by parhamsaremi** [comment]
> > Fixes #181
> 
> Are you sure? I think this is false ^

Actually, I think this PR with the PR that I made to NOnion would solve this problem. In that PR, I converted the System.Exception to IOException and this one catches the NOntion Exceptions.

**Comment by parhamsaremi** [comment]
> > LGTM
> 
> Are you sure? Why are we replacing specific exception types with generic exception types in this PR? I don't understand.

When we catch NOnionExceptions in TorOperations, we have to return them as Result<> type. Since the code in those files was operating with SocketException, I had to change the types to a more generic one, so that I could be able to return both of these errors :thinking:

**Comment by knocte** [comment]
> Actually, I think this PR with the PR that I made to NOnion would solve this problem. In that PR, I converted the System.Exception to IOException and this one catches the NOntion Exceptions.

So?

**Comment by knocte** [comment]
> Since the code in those files was operating with SocketException

I don't understand the reasoning here. The NOnion PR that was recently merged was done so that we didn't need to catch generic exceptions. And this PR introduces generic exceptions?

**Comment by parhamsaremi** [comment]
> > Actually, I think this PR with the PR that I made to NOnion would solve this problem. In that PR, I converted the System.Exception to IOException and this one catches the NOntion Exceptions.
> 
> So?

Should I link that PR too in the description? I didn't know where I should put the link! should I put it in the body? or in the footer?

**Comment by parhamsaremi** [comment]
> > Since the code in those files was operating with SocketException
> 
> I don't understand the reasoning here. The NOnion PR that was recently merged was done so that we didn't need to catch generic exceptions. And this PR introduces generic exceptions?

We don't catch generic expressions :thinking: we are just catching NOnionException but the type of that should have changed so that We could pass both NOnionException and SocketException to the upper level functions. If an System.Excption is thrown from the NOninon, we are not catching it.

**Comment by knocte** [comment]
> We don't catch generic exceptions 🤔 we are just catching NOnionException but the type of that should have changed so that We could pass both NOnionException and SocketException to the upper level functions. If an System.Excption is thrown from the NOninon, we are not catching it.

If you need a type to represent Exception A or Exception B, make a new DU. Do not use base class System.Exception, ever. It invites bad practices.

**Comment by knocte** [comment]
> Should I link that PR too in the description? I didn't know where I should put the link! should I put it in the body? or in the footer?

Why would you want to link that PR in the description?

**Comment by parhamsaremi** [comment]
> > We don't catch generic exceptions thinking we are just catching NOnionException but the type of that should have changed so that We could pass both NOnionException and SocketException to the upper level functions. If an System.Excption is thrown from the NOninon, we are not catching it.
> 
> If you need a type to represent Exception A or Exception B, make a new DU. Do not use base class System.Exception, ever. It invites bad practices.

Hmmm sounds good, I'll work on it :thinking:

**Comment by knocte** [comment]
> Hmmm sounds good, I'll work on it

Actually, are we sure we want to hardcode SocketException in geewallet? Shouldn't NOnion wrap that so that we don't have to?

**Comment by parhamsaremi** [comment]
> > Should I link that PR too in the description? I didn't know where I should put the link! should I put it in the body? or in the footer?
> 
> Why would you want to link that PR in the description?

My understanding was that these two PRs are connected and both of them Fix the issue with each other :thinking:

**Comment by knocte** [comment]
> My understanding was that these two PRs are connected and both of them Fix the issue with each other

That PR is already merged. If we merge this PR, the bug is still not fixed. You're still missing one important thing.

**Comment by knocte** [comment]
> I'm not familiar with SocketExceptions, but I think this idea sounds cleaner

Then try it. (I'm not familiar with them either, I just receive them sometimes and I need to make my code protected against them. I've never looked into their source code.)

**Comment by parhamsaremi** [comment]
> > My understanding was that these two PRs are connected and both of them Fix the issue with each other
> 
> That PR is already merged. If we merge this PR, the bug is still not fixed. You're still missing one important thing.

right :+1:

**Comment by parhamsaremi** [comment]
> > My understanding was that these two PRs are connected and both of them Fix the issue with each other
> 
> That PR is already merged. If we merge this PR, the bug is still not fixed. You're still missing one important thing.

I'll work on updating the NOnion version.

**Comment by parhamsaremi** [comment]
> > Hmmm sounds good, I'll work on it
> 
> Actually, are we sure we want to hardcode SocketException in geewallet? Shouldn't NOnion wrap that so that we don't have to?

For now, I updated the code such that we won't have the problem of generic Exception by defining the case for NOnionException. I think the SocketException needs more investigation.

**Comment by knocte** [comment]
The CI of commit titled `Backend,Tests: update NOnion version` is red because it doesn't even build. It doesn't make sense to separate it from the next commit which fixes the build.

**Comment by parhamsaremi** [comment]
> The CI of commit titled `Backend,Tests: update NOnion version` is red because it doesn't even build. It doesn't make sense to separate it from the next commit which fixes the build.

Sure I'll squash them right now.

**Comment by knocte** [comment]
When merging the last 2 commits, you discarded the message where you explained the use of `new` keyword, why???

**Comment by knocte** [comment]
Screenshot 2022-11-15 at 7 19 44 PM

^ Both commits fix bug 181?

**Comment by parhamsaremi** [comment]
> Screenshot 2022-11-15 at 7 19 44 PM
> 
> ^ Both commits fix bug 181?

My bad. Technically both of them are needed. But I should have only mentioned it in the second one.

**Comment by parhamsaremi** [comment]
> When merging the last 2 commits, you discarded the message where you explained the use of `new` keyword, why???

oops I'll fix this right away.

**Comment by knocte** [comment]
> When merging the last 2 commits, you discarded the message where you explained the use of new keyword, why???

You didn't read this?

**Comment by parhamsaremi** [comment]
> When merging the last 2 commits, you discarded the message where you explained the use of `new` keyword, why???

I answered it and said it was my bad. I'm adding it right now. if you are fixating on the why, I'm not sure I think I might have just missed it when I was squashing two commits.

**Comment by knocte** [comment]
> I answered it and said it was my bad. I'm adding it right now. if you are fixating on the why, I'm not sure I think I might have just missed it when I was squashing two commits.

Sorry it's just that I saw you addressing only 1 of my comments and pushing without addressing my 2nd comment. CI in lightning branch takes long, so if you're gonna push, adress all comments first without pushing, otherwise you clog GitHubActions with useless (obsolete) jobs that make the PR's CI take unnecessary longer.

**Pull request merged**
